### ISSUE TITLE
Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by tbillington** [team-gryff/react-monocle#119]
ran monocle, got

```
monocle -c index.html -j js -b main.6b90ebb85e95149b7fca.js
Starting to strip comments from bundle file...
Took 1.104 seconds to strip comments input bundle file
/usr/local/lib/node_modules/react-monocle/src/previewParser.js:162
  	.reduce((prev, curr) => {
  	 ^

TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at getComponentName (/usr/local/lib/node_modules/react-monocle/src/previewParser.js:162:5)
    at Object.modifySetStateStrings (/usr/local/lib/node_modules/react-monocle/src/previewParser.js:231:35)
    at /usr/local/lib/node_modules/react-monocle/bin/cmd.js:41:38
    at Object.<anonymous> (/usr/local/lib/node_modules/react-monocle/bin/cmd.js:57:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by nhavar** [comment]
Same here

**Comment by mosse** [comment]
+1

**Comment by mbchoa** [comment]
@tbillington @mosse Hey guys!  Thanks for the quick feedback.

Currently, we're supporting Webpack, Gulp, Rollup, Browserify as the main bundling tools that we take account for when parsing through your bundle file. Are you guys using these bundling tools?

Secondly, we require that the bundle file be unmangled/unminified for the purposes of reading through it to get the component information.

**Comment by mbchoa** [comment]
@nhavar Yes, we currently don't support React Router and Redux as a part of the developer's React app.  However, we do have plans for supporting them in the near future.

**Comment by m1n0s** [comment]
@mbchoa, it is nothing have been changed till now, isn't it?

**Comment by DrJukka** [comment]
appears to be the situation also still

**Comment by MomchilGorchev** [comment]
Same here
