### ISSUE TITLE
TypeError: Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by mtrullasp** [team-gryff/react-monocle#124]
With a big bundle file, I get this error:

$ monocle -c index.html -b dist/bundle.js
Starting to strip comments from bundle file...
Took 81.673 seconds to strip comments input bundle file
c:\Users\inf011\AppData\Roaming\npm\node_modules\react-monocle\src\previewParser
.js:162
        .reduce((prev, curr) => {
         ^

TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at getComponentName (c:\Users\inf011\AppData\Roaming\npm\node_modules\react-
monocle\src\previewParser.js:162:5)
    at Object.modifySetStateStrings (c:\Users\inf011\AppData\Roaming\npm\node_mo
dules\react-monocle\src\previewParser.js:231:35)
    at c:\Users\inf011\AppData\Roaming\npm\node_modules\react-monocle\bin\cmd.js
:41:38
    at Object.<anonymous> (c:\Users\inf011\AppData\Roaming\npm\node_modules\reac
t-monocle\bin\cmd.js:57:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

**Comment by mbchoa** [comment]
Hey! Thank you for the feedback.  

We will be closing this and using #119 as the main thread for this issue.
