### ISSUE TITLE
Strip Comment failed, and the tool stop working

### ISSUE THREAD

**Issue by mgmgpyaesonewin** [team-gryff/react-monocle#148]
```
/.nvm/versions/node/v8.5.0/lib/node_modules/react-monocle/node_modules/extract-comments/lib/comments.js:55
      throw err;
      ^
Error: Line 1: Unexpected token <
    at constructError (/Users/pyaesone/.nvm/versions/node/v8.5.0/lib/node_modules/react-monocle/node_modules/esprima-extract-comments/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/pyaesone/.nvm/versions/node/v8.5.0/lib/node_modules/react-monocle/node_modules/esprima-extract-comments/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/pyaesone/.nvm/versions/node/v8.5.0/lib/node_modules/react-monocle/node_modules/esprima-extract-comments/node_modules/esprima/esprima.js:2500:13)
    at throwUnexpectedToken (/Users/pyaesone/.nvm/versions/node/v8.5.0/lib/node_modules/react-monocle/node_modules/esprima-extract-comments/node_modules/esprima/esprima.js:2505:15)
    at parsePrimaryExpression (/Users/pyaesone/.nvm/versions/node/v8.5.0/lib/node_modules/react-monocle/node_modules/esprima-extract-comments/node_modules/esprima/esprima.js:3307:13)
    at inheritCoverGrammar (/Users/pyaesone/.nvm/versions/node/v8.5.0/lib/node_modules/react-monocle/node_modules/esprima-extract-comments/node_modules/esprima/esprima.js:2681:18)
    at parseLeftHandSideExpressionAllowCall (/Users/pyaesone/.nvm/versions/node/v8.5.0/lib/node_modules/react-monocle/node_modules/esprima-extract-comments/node_modules/esprima/esprima.js:3414:20)
    at inheritCoverGrammar (/Users/pyaesone/.nvm/versions/node/v8.5.0/lib/node_modules/react-monocle/node_modules/esprima-extract-comments/node_modules/esprima/esprima.js:2681:18)
    at parsePostfixExpression (/Users/pyaesone/.nvm/versions/node/v8.5.0/lib/node_modules/react-monocle/node_modules/esprima-extract-comments/node_modules/esprima/esprima.js:3490:16)
    at parseUnaryExpression (/Users/pyaesone/.nvm/versions/node/v8.5.0/lib/node_modules/react-monocle/node_modules/esprima-extract-comments/node_modules/esprima/esprima.js:3550:20)
```

**Comment by bastiandiaz** [comment]
Same problem here.
